package com.kpioneer.dataobject;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.id
     *
     * @mbg.generated Thu Mar 19 16:47:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_name
     *
     * @mbg.generated Thu Mar 19 16:47:51 CST 2020
     */
    private String promoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.start_date
     *
     * @mbg.generated Thu Mar 19 16:47:51 CST 2020
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.item_id
     *
     * @mbg.generated Thu Mar 19 16:47:51 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_item_price
     *
     * @mbg.generated Thu Mar 19 16:47:51 CST 2020
     */
    private BigDecimal promoItemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.end_date
     *
     * @mbg.generated Thu Mar 19 16:47:51 CST 2020
     */
    private Date endDate;


}