package com.kpioneer.controller.viewobject;

import lombok.Data;

/**
 * Created by hzllb on 2018/11/11.
 */
@Data
public class UserVO {
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbg.generated Tue Mar 17 20:19:31 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbg.generated Tue Mar 17 20:19:31 CST 2020
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbg.generated Tue Mar 17 20:19:31 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.telphone
     *
     * @mbg.generated Tue Mar 17 20:19:31 CST 2020
     */
    private String telphone;
}
